# Generated by Django 2.1.3 on 2018-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exapmle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='제목')),
                ('content', models.CharField(max_length=100, verbose_name='내용')),
            ],
            options={
                'verbose_name': '예제',
                'verbose_name_plural': '예제',
            },
        ),
    ]
