# Generated by Django 2.1.3 on 2018-11-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exapmle',
            new_name='Example',
        ),
    ]
